language: node_js

node_js:
- node

cache: yarn

before_script:
  - yarn update-browsers

before_deploy:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master

addons:
  sauce_connect: true

env:
  global:
    - SAUCE_USERNAME=forabi-webceph-machine
    - secure: "o2qxW+qNEgn47CB6rcb4cU6PnP2rpkLqUvDMF/E16wfzJEwbGov7mNmRUYCJrwkuBQ6CNokMwO7Yk7Q7VYgj24AzR9J7CGvCV
0I3QoGhqmmt90/es0WICAR/Hf4JdeY5uOjCy2DvRD9YsXRfCnXIIuYsV86crxEOPG/aHXrkyfd98k29LREPHcVjeXyWCLvqimvfYGF230nmS
vnxtcqlxzBGOkPDADP6qfLBjy6XR9RMoZODSbVKukrmniZ7Z0y6yNs4EOjgUPMpAQ5Qg6Ehrbz0y2cHRE013vkuRSpd5iW2c/1GDBrJFlSwz
Sla3QVqVWHHE60rB1dyoHVWnpznmgn8E+XKcXJS0N8CsBACom0EiMdJZYp+HTu4a6WxFo8V/GJ/idUeSQR+q4He7kT2WdmTeVyT/RzNIs/j4
R0wBe9WIluojYieIT51AJKhVfaGipixPVZk8aEsdRJQHm1ZToYIqej1m/QQxrFQ9He7cfGgjBQglCtK87YF6MACavTkXwdiL40ikTkiKC9Bh
54BHfLzwhiaWd8QEBHufgPlXRq2254+6TO+3XucykxAD+L3dN5BqILQDHtbvGBmkB3TmRO9U0BEC1amzSqKPP05gizhXPXzFrXjEJQcU2uGR
lq4JgNW1gDBdH5VQtZ5lF73ymCFnb4RTfHHThYpt9bB6/I="