language: node_js

node_js:
- node

cache: yarn

before_script:
  - yarn update-browsers

before_deploy:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master

addons:
  sauce_connect: true
