language: node_js

node_js:
- node

cache: yarn

before_script:
  - yarn update-browsers
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

script:
  - yarn test
  - cat ./coverage/coverage.lcov | ./node_modules/coveralls/bin/coveralls.js
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

before_deploy:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master

addons:
  sauce_connect: true
